export const MAX_DECK_SIZE = 20;
export const MAX_BENCH_SIZE = 3;
export const MAX_HAND_SIZE = 10;
export const STARTING_HAND_SIZE = 5;
export const CARDS_PER_PACK = 5;
export const MAX_STORED_PACKS = 2;
export const PACK_RECHARGE_MS = 12 * 60 * 60 * 1000; // 12 hours
export const MAX_CARD_COPIES = 2;
export const MAX_SENSEI_COPIES = 1;
export const WIN_POINTS = 3;
export const LEGENDARY_KO_POINTS = 2;
export const REGULAR_KO_POINTS = 1;
export const MAX_TURNS = 30;
export const BURN_DAMAGE = 20;
export const POISON_DAMAGE = 10;
export const CONFUSION_SELF_DAMAGE = 30;
// Pokemon TCGP weakness is flat +20 damage (not ×2 like Standard TCG).
export const WEAKNESS_BONUS = 20;
export const XP_PER_WIN = 50;
export const XP_PER_LOSS = 10;
export const XP_PER_PACK = 25;
